import { get, put } from '@vercel/blob';
import { runDisplayStatus } from '../../server/lib/dashboard.js';

/**
 * The run history, on Vercel Blob, because there is nowhere else to put it.
 *
 * The local API keeps this in state/runs.json on disk. A Vercel function's
 * filesystem is read-only apart from a 500 MB /tmp scratch that is discarded when
 * the instance is recycled, so every write there would silently vanish. Blob is
 * already in use for the reels — same store, `reels/` prefix — so the state
 * joins them under `state/` rather than introducing a second dependency.
 *
 * The two backends are not interchangeable, and the difference shows up in one
 * place: CI regenerates state/runs.json from scratch on every run, so a run
 * deleted from the dashboard comes straight back the next morning. Hence
 * tombstones.
 *
 * ## Tombstones
 *
 * `state/tombstones.json` records the ids a human has removed or settled from the
 * console. publishDashboard.js filters them out of what it uploads, so the daily
 * CI run cannot resurrect a reel that was deleted on purpose. Without this the
 * delete button would appear to work and then undo itself ~20 hours later, which
 * is the kind of bug that gets a feature removed rather than fixed.
 *
 * ## Concurrency
 *
 * Read-modify-write, not transactional. `put` accepts an `ifMatch` precondition
 * and this could use it, but the only writer besides CI is one person clicking
 * one button, and a retry loop around a 412 buys nothing at that contention level.
 * Two clicks landing in the same second is the whole risk, and the loser's write
 * is a state file, not a deletion of a reel.
 */

const PREFIX = 'state';

export const PATHS = {
  runs: `${PREFIX}/runs.json`,
  pending: `${PREFIX}/pending.json`,
  covered: `${PREFIX}/covered.json`,
  tombstones: `${PREFIX}/tombstones.json`
};

// Ids are ISO timestamps generated by the orchestrator, so this rejects nothing
// real while keeping a caller-controlled id from becoming a Blob pathname.
const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;

// The run log outlives its own reels, but a tombstone has no such reason to
// accumulate: once CI's state file has rolled past an id it cannot come back, so
// the list is bounded well below the 200 covered events keep.
const MAX_TOMBSTONES = 100;

export class StateError extends Error {
  constructor(message, status = 500) {
    super(message);
    this.name = 'StateError';
    this.status = status;
  }
}

// ---- pure transforms, exported so the retention rules can be tested --------

export function emptyTombstones() {
  return { runs: [], pending: [] };
}

/** Drops deleted runs from an incoming history — used by publishDashboard.js. */
export function applyTombstones(runs, tombstones) {
  const gone = new Set(tombstones?.runs ?? []);
  if (!gone.size) return runs;
  return runs.filter((r) => !gone.has(r?.id));
}

/** Same for queue entries, so a rejection survives the next CI publish. */
export function applyPendingTombstones(pending, tombstones) {
  const settled = new Set(tombstones?.pending ?? []);
  if (!settled.size) return pending;
  return pending.filter((p) => !settled.has(p?.id));
}

export function addTombstone(tombstones, kind, id) {
  const next = { ...emptyTombstones(), ...tombstones };
  const list = Array.isArray(next[kind]) ? next[kind] : [];
  if (list.includes(id)) return next;
  next[kind] = [id, ...list].slice(0, MAX_TOMBSTONES);
  return next;
}

/**
 * Mirrors server/lib/state.js resolvePendingPost: throws for a missing or
 * already-resolved entry, so a double-click cannot silently overwrite an outcome
 * that was already reported.
 */
export function applyResolution(pending, id, status, detail = {}) {
  const found = pending.find((p) => p.id === id);
  if (!found) throw new StateError(`Queue entry not found: ${id}`, 404);
  if (found.status !== 'pending') throw new StateError(`Queue entry ${id} is already ${found.status}`, 409);

  found.status = status;
  found.resolvedAt = new Date().toISOString();
  Object.assign(found, detail);
  return found;
}

export function assertSafeId(id) {
  if (!SAFE_ID.test(String(id ?? ''))) throw new StateError('Malformed run id', 400);
  return id;
}

// ---- blob i/o -------------------------------------------------------------

async function readJson(pathname, fallback) {
  let res;
  try {
    // useCache: false bypasses the CDN. The alternative is a delete that appears
    // to work and then reappears on the next poll, because the edge is still
    // serving the pre-delete body. One operator polling every few seconds is not
    // enough traffic to make an origin read per poll worth optimising away.
    res = await get(pathname, { useCache: false });
  } catch (err) {
    throw new StateError(`Could not read ${pathname} from Blob: ${err.message}`);
  }
  if (!res?.stream) return fallback;

  const text = await new Response(res.stream).text();
  try {
    return JSON.parse(text);
  } catch {
    // A truncated or hand-edited body is a broken store, not an empty one. The
    // fallback is the empty state, which shows "no runs yet" — recoverable.
    return fallback;
  }
}

async function writeJson(pathname, data) {
  try {
    await put(pathname, `${JSON.stringify(data, null, 2)}\n`, {
      access: 'public',
      contentType: 'application/json',
      // Deterministic pathname: CI and the dashboard both write these keys, and
      // a random suffix would leave an orphan blob behind on every overwrite.
      addRandomSuffix: false,
      allowOverwrite: true
    });
  } catch (err) {
    throw new StateError(`Could not write ${pathname} to Blob: ${err.message}`);
  }
}

// ---- runs -----------------------------------------------------------------

export async function loadTombstones() {
  return { ...emptyTombstones(), ...(await readJson(PATHS.tombstones, emptyTombstones())) };
}

export async function loadRuns() {
  const data = await readJson(PATHS.runs, { runs: [] });
  return Array.isArray(data.runs) ? data.runs : [];
}

export async function getRun(id) {
  assertSafeId(id);
  return (await loadRuns()).find((r) => r.id === id) || null;
}

/**
 * Removes a run and records the tombstone. The tombstone is written *after* the
 * history, so a failure between the two leaves a run that is merely still
 * visible — recoverable — rather than a deletion that CI will undo with no
 * record that anyone asked for it.
 */
export async function deleteRun(id) {
  assertSafeId(id);
  const runs = await loadRuns();
  const next = runs.filter((r) => r.id !== id);
  if (next.length === runs.length) throw new StateError('Run not found', 404);

  await writeJson(PATHS.runs, { runs: next });
  const tombstones = addTombstone(await loadTombstones(), 'runs', id);
  await writeJson(PATHS.tombstones, tombstones);
  return id;
}

// ---- pending approvals ----------------------------------------------------

export async function loadPendingPosts() {
  const data = await readJson(PATHS.pending, { pending: [] });
  return Array.isArray(data.pending) ? data.pending : [];
}

export async function listPendingPosts({ includeResolved = false } = {}) {
  const all = await loadPendingPosts();
  return includeResolved ? all : all.filter((p) => p.status === 'pending');
}

export async function getPendingPost(id) {
  assertSafeId(id);
  return (await loadPendingPosts()).find((p) => p.id === id) || null;
}

export async function resolvePendingPost(id, status, detail = {}) {
  assertSafeId(id);
  const pending = await loadPendingPosts();
  applyResolution(pending, id, status, detail);

  await writeJson(PATHS.pending, { pending });
  const tombstones = addTombstone(await loadTombstones(), 'pending', id);
  await writeJson(PATHS.tombstones, tombstones);
  return pending.find((p) => p.id === id);
}

// ---- covered events -------------------------------------------------------

export async function loadCoveredEvents() {
  const data = await readJson(PATHS.covered, { events: [] });
  return Array.isArray(data.events) ? data.events : [];
}

export { runDisplayStatus };
